1. tentukan library yang digunakan

In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score


2. load dataset

In [13]:
df = pd.read_csv('womanPregnancy.csv', delimiter=';')
print(df.head())

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86          1
1   35         140           90  13.0      98.0         70          1
2   29          90           70   8.0     100.0         80          1
3   30         140           85   7.0      98.0         70          1
4   35         120           60   6.1      98.0         76          0


In [14]:
df.shape

(1014, 7)

In [18]:
df['RiskLevel'].value_counts()

RiskLevel
 0    406
-1    336
 1    272
Name: count, dtype: int64

In [19]:
#memisahkan data dan label
X = df.drop (columns = 'RiskLevel', axis=1)
Y = df['RiskLevel']
print(X)
print(Y)

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0      25         130           80  15.0      98.0         86
1      35         140           90  13.0      98.0         70
2      29          90           70   8.0     100.0         80
3      30         140           85   7.0      98.0         70
4      35         120           60   6.1      98.0         76
...   ...         ...          ...   ...       ...        ...
1009   22         120           60  15.0      98.0         80
1010   55         120           90  18.0      98.0         60
1011   35          85           60  19.0      98.0         86
1012   43         120           90  18.0      98.0         70
1013   32         120           65   6.0     101.0         76

[1014 rows x 6 columns]
0       1
1       1
2       1
3       1
4       0
       ..
1009    1
1010    1
1011    1
1012    1
1013   -1
Name: RiskLevel, Length: 1014, dtype: int64


3. standarisasi/transformasi data

In [15]:
scaler = StandardScaler()

In [16]:
scaler.fit(X)
standarized_data = scaler.transform(X)
print(standarized_data)

[[-0.36173812  0.91339632  0.25502279  1.90589019 -0.4852155   1.44695615]
 [ 0.38077697  1.45702716  0.97553854  1.29833966 -0.4852155  -0.53208757]
 [-0.06473208 -1.26112705 -0.46549297 -0.22053665  0.97388449  0.70481475]
 ...
 [ 0.38077697 -1.53294248 -1.18600873  3.12099124 -0.4852155   1.44695615]
 [ 0.97478904  0.36976548  0.97553854  2.81721597 -0.4852155  -0.53208757]
 [ 0.15802244  0.36976548 -0.82575085 -0.82808717  1.70343448  0.21005383]]


In [17]:
X = standarized_data
Y = df['RiskLevel']
print(X)
print(Y)

[[-0.36173812  0.91339632  0.25502279  1.90589019 -0.4852155   1.44695615]
 [ 0.38077697  1.45702716  0.97553854  1.29833966 -0.4852155  -0.53208757]
 [-0.06473208 -1.26112705 -0.46549297 -0.22053665  0.97388449  0.70481475]
 ...
 [ 0.38077697 -1.53294248 -1.18600873  3.12099124 -0.4852155   1.44695615]
 [ 0.97478904  0.36976548  0.97553854  2.81721597 -0.4852155  -0.53208757]
 [ 0.15802244  0.36976548 -0.82575085 -0.82808717  1.70343448  0.21005383]]
0       1
1       1
2       1
3       1
4       0
       ..
1009    1
1010    1
1011    1
1012    1
1013   -1
Name: RiskLevel, Length: 1014, dtype: int64


4. memisahkan data training dan data testing

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape) 

(1014, 6) (811, 6) (203, 6)


5. membuat data latih menggunakan algoritma SVM

In [19]:
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

6. membuat model evaluasi untuk mengukur tingkat akurasi

In [20]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Akurasi data training adalah = ', training_data_accuracy)

Akurasi data training adalah =  0.6374845869297164


In [21]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Akurasi data testing adalah = ', test_data_accuracy)

Akurasi data testing adalah =  0.6600985221674877


7. membuat model prediksi

In [22]:
input_data = (25, 130, 80, 15, 98, 1) 

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
    print('Wanita hamil tersebut memiliki resiko yang kecil')
    if  (prediction[-1] == -1):
       print('Wanita hamil tersebut memiliki resiko yang sedang')
else :
    print('Wanita hamil tersebut memiliki resiko')

[[-0.36173812  0.91339632  0.25502279  1.90589019 -0.4852155  -9.06671358]]
[-1]
Wanita hamil tersebut memiliki resiko


C:\Users\putri\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


8. membuat model

In [24]:
import pickle
filename = 'womanPregnancy.sav'
pickle.dump(classifier, open(filename,'wb'))

In [ ]:
!python -m streamlit run womanPregnancy_streamlit.py

In [2]:
!pip3 install streamlit